# This is a generated file. Not intended for manual editing.
services:
  aw_daemon:
    build:
      context: "/Users/acrona/Desktop/AW_Daemon"
      dockerfile: "AW_Daemon/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/AW_Daemon.dll"
    environment:
      DOTNET_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "aw_daemon:dev"
    ports: []
    volumes:
    - "/Users/acrona/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/acrona/Desktop/AW_Daemon/AW_Daemon:/app:rw"
    - "/Users/acrona/Desktop/AW_Daemon:/src:rw"
    working_dir: "/app"
